- name: Enable UFW
  ufw:
    state: enabled

- name: Set logging
  ufw:
    logging: on

- name: Allow SSH
  ufw:
    rule: allow
    name: OpenSSH

- name: Rate limit SSH connections
  ufw:
    rule: limit
    port: ssh
    proto: tcp
